import type { Pooja } from './PoojaCard'

export const ALL_POOJAS: Pooja[] = [
  {
    id: 101,
    name: 'Rudrabhishek',
    temple: 'Kashi Vishwanath',
    templeId: 1,
    emoji: '🪔',
    price: 1100,
    originalPrice: 1500,
    duration: '45 min',
    rating: 4.9,
    reviews: 3240,
    benefit: 'Health & Prosperity',
    tag: 'Best Seller',
    tagVariant: 'maroon',
    description: 'Sacred Shiv abhishek with panchamrit, milk & bel patra. Chanting of Shiva Mahimna Stotram with 108 names.',
    category: 'Shiva Puja',
  },
  {
    id: 102,
    name: 'Satyanarayan Katha',
    temple: 'Siddhivinayak',
    templeId: 3,
    emoji: '🌸',
    price: 2100,
    originalPrice: 2800,
    duration: '2 hrs',
    rating: 4.8,
    reviews: 1890,
    benefit: 'Success & Peace',
    tag: 'Popular',
    tagVariant: 'saffron',
    description: 'Complete Satyanarayan Katha with proper vidhi, panchamrit abhishek and prasad offering.',
    category: 'Vishnu Puja',
  },
  {
    id: 103,
    name: 'Navgrah Puja',
    temple: 'Kashi Vishwanath',
    templeId: 1,
    emoji: '⭐',
    price: 1500,
    originalPrice: 2000,
    duration: '60 min',
    rating: 4.7,
    reviews: 2100,
    benefit: 'Remove Obstacles',
    tag: 'Trending',
    tagVariant: 'gold',
    description: 'Powerful Navgrah Shanti puja to appease all nine planets and remove astrological doshas.',
    category: 'Grah Shanti',
  },
  {
    id: 104,
    name: 'Ganesh Pooja',
    temple: 'Siddhivinayak',
    templeId: 3,
    emoji: '🐘',
    price: 800,
    originalPrice: 1100,
    duration: '30 min',
    rating: 4.9,
    reviews: 4500,
    benefit: 'New Beginnings',
    tag: 'Must Book',
    tagVariant: 'saffron',
    description: 'Auspicious Ganpati puja with modak, durva and red flowers. Ideal before new ventures.',
    category: 'Ganesh Puja',
  },
  {
    id: 105,
    name: 'Lakshmi Puja',
    temple: 'Tirupati Balaji',
    templeId: 2,
    emoji: '💛',
    price: 1200,
    originalPrice: 1600,
    duration: '45 min',
    rating: 4.8,
    reviews: 2900,
    benefit: 'Wealth & Fortune',
    tag: 'Popular',
    tagVariant: 'saffron',
    description: 'Mahalakshmi puja with lotus flowers, gold coins offering and Lakshmi Ashtottara Shatanamavali.',
    category: 'Lakshmi Puja',
  },
  {
    id: 106,
    name: 'Mahamrityunjaya Jaap',
    temple: 'Kashi Vishwanath',
    templeId: 1,
    emoji: '🙏',
    price: 3100,
    originalPrice: 4000,
    duration: '3 hrs',
    rating: 4.9,
    reviews: 1560,
    benefit: 'Health & Long Life',
    tag: 'Sacred',
    tagVariant: 'maroon',
    description: '1,25,000 Mahamrityunjaya mantra jaap performed by experienced pandits for health and longevity.',
    category: 'Shiva Puja',
  },
  {
    id: 107,
    name: 'Durga Saptashati Path',
    temple: 'Vaishno Devi',
    templeId: 4,
    emoji: '🔱',
    price: 2500,
    originalPrice: 3500,
    duration: '4 hrs',
    rating: 4.9,
    reviews: 2200,
    benefit: 'Protection & Courage',
    tag: 'Navratri Special',
    tagVariant: 'maroon',
    description: 'Complete recitation of Durga Saptashati (700 verses) with Navarna mantra and havan.',
    category: 'Devi Puja',
  },
  {
    id: 108,
    name: 'Vishnu Sahasranaam',
    temple: 'Tirupati Balaji',
    templeId: 2,
    emoji: '🌺',
    price: 1800,
    originalPrice: 2400,
    duration: '90 min',
    rating: 4.8,
    reviews: 1340,
    benefit: 'Moksha & Prosperity',
    tag: 'Sacred',
    tagVariant: 'maroon',
    description: 'Recitation of 1000 names of Lord Vishnu with Tulsi, flowers and panchamrit abhishek.',
    category: 'Vishnu Puja',
  },
  {
    id: 109,
    name: 'Kaal Sarp Dosh Puja',
    temple: 'Mahakaleshwar',
    templeId: 8,
    emoji: '🐍',
    price: 5100,
    originalPrice: 7000,
    duration: '5 hrs',
    rating: 4.9,
    reviews: 980,
    benefit: 'Remove Kaal Sarp Dosh',
    tag: 'Specialized',
    tagVariant: 'gold',
    description: 'Powerful puja at Trimbakeshwar with complete Kaal Sarp Dosh Nivaran rituals.',
    category: 'Dosh Nivaran',
  },
  {
    id: 110,
    name: 'Sunderkand Path',
    temple: 'Kashi Vishwanath',
    templeId: 1,
    emoji: '🐒',
    price: 1100,
    originalPrice: 1500,
    duration: '2 hrs',
    rating: 4.7,
    reviews: 2800,
    benefit: 'Remove Obstacles & Fear',
    tag: 'Popular',
    tagVariant: 'saffron',
    description: 'Devotional recitation of Sunderkand from Ramcharitmanas by trained pandits.',
    category: 'Ram Puja',
  },
  {
    id: 111,
    name: 'Griha Pravesh Puja',
    temple: 'Siddhivinayak',
    templeId: 3,
    emoji: '🏡',
    price: 3500,
    originalPrice: 4500,
    duration: '3 hrs',
    rating: 4.8,
    reviews: 1100,
    benefit: 'New Home Blessings',
    tag: 'Home Ceremony',
    tagVariant: 'green',
    description: 'Complete Griha Pravesh puja with Vastu Shanti, havan and Navgrah puja for new home.',
    category: 'Special Ceremony',
  },
  {
    id: 112,
    name: 'Pind Daan & Pitru Puja',
    temple: 'Kashi Vishwanath',
    templeId: 1,
    emoji: '🕊️',
    price: 2100,
    originalPrice: 2800,
    duration: '2 hrs',
    rating: 4.9,
    reviews: 670,
    benefit: 'Ancestor Blessings',
    tag: 'Ancestral',
    tagVariant: 'gold',
    description: 'Sacred Pind Daan and Shradh ceremony at the holy Ghats of Varanasi for ancestors.',
    category: 'Pitru Puja',
  },
]

export const POOJA_CATEGORIES = [
  'All',
  'Shiva Puja',
  'Vishnu Puja',
  'Ganesh Puja',
  'Lakshmi Puja',
  'Devi Puja',
  'Grah Shanti',
  'Dosh Nivaran',
  'Special Ceremony',
  'Pitru Puja',
]